// <auto-generated />
using System;
using InclusaoDiversidade.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InclusaoDiversidade.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Completion", b =>
                {
                    b.Property<int>("CompletionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletionId"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrollmentEnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompletionId");

                    b.HasIndex("EnrollmentEnrollmentId");

                    b.ToTable("Completions");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.DiversityReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("FemaleCount")
                        .HasColumnType("int");

                    b.Property<int>("MaleCount")
                        .HasColumnType("int");

                    b.Property<int>("OtherCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalEmployees")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("DepartmentDepartmentId");

                    b.ToTable("DiversityReports");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.EmailOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailOutbox");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentDepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("EmployeeEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainingTrainingId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("EmployeeEmployeeId");

                    b.HasIndex("TrainingTrainingId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Completion", b =>
                {
                    b.HasOne("InclusaoDiversidade.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("Completions")
                        .HasForeignKey("EnrollmentEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.DiversityReport", b =>
                {
                    b.HasOne("InclusaoDiversidade.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Employee", b =>
                {
                    b.HasOne("InclusaoDiversidade.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("InclusaoDiversidade.Domain.Entities.Employee", "Employee")
                        .WithMany("Enrollments")
                        .HasForeignKey("EmployeeEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InclusaoDiversidade.Domain.Entities.Training", "Training")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingTrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("InclusaoDiversidade.Domain.Entities.Training", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
